### ISSUE TITLE
Проблема с отправкой одинаковых сообщений

### ISSUE THREAD

**Issue by cvbn127** [serega404/VodokanalBot#1]
В базе хранятся тексты сообщения, а новые сообщения на сайте могут совпадать с сообщениями в базе.  
В результате такие дублирующиеся сообщения не отправятся в канал.
Наверное и дату сообщения в базе стоит хранить(например конкатенировать строку с датой и строку с текстом сообщения).

![S31005-10200021(1)](https://github.com/serega404/VodokanalBot/assets/12460992/27a7c2b0-b9a4-4da8-aa7a-a85c7a8fd21a)

**Comment by serega404** [comment]
Привет, спасибо за issue, ранее дата учитывалась, но от неё пришлось отказаться, не помню точно из-за чего, но вроде на это повлиял формат даты предоставляемый водоканалом, так как дату заполняет человек, то иногда можно было получить дату в формате  1.0.2.23г.

Так же можно увидеть что год всегда заполняется по-разному, скорее всего это связанно с тем что эти сообщения выкладывают около 3‑х разных людей 
![image](https://github.com/serega404/VodokanalBot/assets/38862669/85d44e1b-1dbc-404d-91fd-dd15f58e33e8))

**Comment by cvbn127** [comment]
ну так я не предлагаю дату эту дату отправлять в тг
я предлагаю её учитывать при хранении в бд, для того чтобы гарантированно отличать два одинаковых сообщения из разных дней. При таком использовании не важно в каком формате дата представлена.

**Comment by serega404** [comment]
Я после отправки моего сообщения понял суть issue. Сделаю, спасибо за информацию.

**Comment by cvbn127** [comment]
спасибо :)
